name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/build-windows.yml'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyInstaller==6.13.0

      - name: Build single-file exe
        shell: bash
        run: |
          python build_windows.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MouseClicker_Win11_single_file
          path: |
            dist/MouseClicker_Win11.exe
            release/windows/**